version: '2'
services:
  php:
    image: yiisoftware/yii2-php:8.2-apache   # Updated to PHP 8.2 image
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '8080:80'  # Changed the port to 8080 as requested

