version: '3.8'

services:
  php:
    image: nishankkoul/pearlthoughts-devops-assignment:2.6
    volumes:
      - ./:/app:delegated
    ports:
      - '8080:8080'
    restart: always
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
      update_config:
        parallelism: 1
        delay: 10s
    healthcheck:
      test: ["CMD", "curl", "--silent", "--fail", "http://localhost:8080/"]
      interval: 30s
      retries: 3
      timeout: 10s
      start_period: 10s

