name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx for multi-platform builds (optional)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Step 3: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub username stored in GitHub Secrets
          password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub password stored in GitHub Secrets

      # Step 4: Build and push Docker image to Docker Hub
      - name: Build and push Docker image
        run: |
          docker build -t nishankkoul/pearlthoughts-devops-assignment:latest .
          docker push nishankkoul/pearlthoughts-devops-assignment:latest

      # Step 5: SSH into EC2 and deploy to Docker Swarm
      - name: SSH into EC2 and deploy to Docker Swarm
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}  # EC2 public IP from GitHub Secrets
          username: ubuntu  # EC2 default user for Ubuntu instances
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}  # Private SSH key stored in GitHub Secrets
          port: 22
          script: |
            # Pull the latest image
            docker pull nishankkoul/pearlthoughts-devops-assignment:latest
            # Update the Docker Swarm service with the new image
            docker service update --image nishankkoul/pearlthoughts-devops-assignment:latest myapp_php

            # Optional: Implement rollback on failure
            if [ $? -ne 0 ]; then
              echo "Deployment failed, rolling back..."
              docker service update --rollback myapp_php
            fi
